cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update_quantity/', views.update_quantity, name="update_quantity"),
    path('remove_item/', views.remove_item, name="remove_item")
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path('verify_phone/', views.verify_phone, name="verify_phone"),
    path('verify_code', views.verify_code, name="verify_code"),
    path('crate_order/', views.create_order, name="create_order"),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
    path('order_list/', views.orders_list, name='order_list'),
    path('order_detail/<int:id>/', views.order_detail, name="order_detail")
]

sabzshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('shop.urls', namespace='shop')),
    path("cart/", include('cart.urls', namespace='cart')),
    path('order/',include('order.urls',namespace="order"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from shop.models import Product


@require_POST
def add_to_cart(request, product_id):
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.add(product)
        context = {
            'item_count': len(cart),
            'total_price': cart.total_price()
        }
        return JsonResponse(context)
    except:
        return JsonResponse({'error': 'invalid request'})


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart-detail.html', {'cart': cart})


@require_POST
def update_quantity(request):
    item_id = request.POST.get('item_id')
    action = request.POST.get('action')
    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        if action == 'add':
            cart.add(product)
        elif action == 'decrease':
            cart.decrease(product)
        context = {
            'item_count': len(cart),
            'total_price': cart.total_price(),
            'quantity': cart.cart[item_id]['quantity'],
            'total': cart.cart[item_id]['quantity'] * cart.cart[item_id]['price'],
            'success': True,
            'final_price': cart.final_price(),
            'post_price': cart.get_post_price()
        }
        return JsonResponse(context)
    except:
        return JsonResponse({'success': False, 'error': 'item not found'})


@require_POST
def remove_item(request):
    item_id = request.POST.get('item-id')
    try:
        product = get_object_or_404(Product, id=item_id)
        cart = Cart(request)
        cart.remove(product)
        context = {
            'item_count': len(cart),
            'total_price': cart.total_price(),
            'final_price': cart.final_price(),
            'post_price': cart.get_post_price(),
            'success': True,
        }
        return JsonResponse(context)
    except:
        return JsonResponse({'success': False, "error": 'Item NOt Found'})

cart/templates/cart/cart-detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}cart{% endblock %}
{% block content %}
    {% for item in cart %}
        <div class="product-item" data-item-id="{{ item.product.id }}">
            <a href="{{ item.product.get_absolute_url }}"><h2>{{ item.product.name }}</h2></a>
            {% for img in item.product.images.all %}
                <img src="{{ img.file.url }}" alt="Not found" style="width: fit-content" height="150px">
            {% endfor %}
            <br>
            Price : {{ item.price }}
            <br>
            Quantity : <span id="item-quantity-{{ item.product.id }}">{{ item.quantity }}</span>
            <br>
            Total price : <span id="item-total-{{ item.product.id }}">{{ item.total }}</span>
            <br>
            <button type="button" class="quantity-add">+</button>
            |
            <button type="button" class="quantity-decrease">-</button>
            <br>
            <button type="button" class="quantity-remove">Remove</button>
            <hr>
        </div>
    {% endfor %}
    <h3>
        All products total price : <span id="item-total-price">{{ cart.total_price }}</span>
        <br>
        Post price : <span id="item-post-price">{{ cart.get_post_price }}</span>
        <br>
        Final price : <span id="item-final-price">{{ cart.final_price }}</span>
    </h3>
    <a href="{% url 'order:verify_phone' %}"><button type="button">Completing purchase</button></a>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function () {
            $('.quantity-add').on('click', function () {
                updateQuantity($(this).closest('.product-item').data('item-id'), 'add');
            });
            $('.quantity-decrease').on('click', function () {
                updateQuantity($(this).closest('.product-item').data('item-id'), 'decrease');
            });
            $('.quantity-remove').on('click', function () {
                removeItem($(this).closest('.product-item').data('item-id'));
            });

            function updateQuantity(ItemId, action) {
                $.ajax({
                    type: 'POST',
                    url: '{% url "cart:update_quantity" %}',
                    data: {'item_id': ItemId, 'action': action, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    success: function (data) {
                        if (data.success) {
                            $('#item-count').text(data.item_count);
                            $('#total-price').text(data.total_price);
                            $('#item-quantity-' + ItemId).text(data.quantity);
                            $('#item-total-' + ItemId).text(data.total);
                            $('#item-total-price').text(data.total_price);
                            $('#item-post-price').text(data.post_price);
                            $('#item-final-price').text(data.fianl_price);
                        } else {
                            alert('Error update quantity!');
                        }
                    }
                });
            }
        });

        function removeItem(itemId) {
            $.ajax({
                type: 'POST',
                url: '{% url 'cart:remove_item' %}',
                data: {'item-id': itemId, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                success: function (data) {
                    if (data.success) {
                        $('#item-count').text(data.item_count);
                        $('#total-price').text(data.total_price);
                        $('#item-total-price').text(data.total_price);
                        $('#item-post-price').text(data.post_price);
                        $('#item-final-price').text(data.final_price);
                        $(`.product-item[data-item-id=${itemId}]`).remove();
                    }else{alert('Error updating quantity!')}
                }
            });
        }
    </script>
{% endblock %}