cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update_quantity/', views.update_quantity, name="update_quantity"),
    path('remove_item/', views.remove_item, name="remove_item")
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"
urlpatterns = [
    path('verify_phone/', views.verify_phone, name="verify_phone"),
    path('verify_code', views.verify_code, name="verify_code"),
    path('crate_order/', views.create_order, name="create_order"),
    path('request/', views.send_request, name='request'),
    path('verify/', views.verify, name='verify'),
    path('order_list/', views.orders_list, name='order_list'),
    path('order_detail/<int:id>/', views.order_detail, name="order_detail")
]

sabzshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('shop.urls', namespace='shop')),
    path("cart/", include('cart.urls', namespace='cart')),
    path('order/',include('order.urls',namespace="order"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "shop"
urlpatterns = [
    path('', views.profile, name="profile"),
    path('products/', views.product_list, name='products'),
    path('products/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('products_filter/<str:ordering>/', views.product_list, name='products_by_filter'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product'),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.register, name='register'),

]

order/models.py
from django.db import models
from account.models import ShopUser
from shop.models import Product


class Order(models.Model):
    buyer = models.ForeignKey(ShopUser, related_name="orders", on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone = models.CharField(max_length=11)
    address = models.TextField()
    postal_code = models.CharField(max_length=10)
    province = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [models.Index(fields=['-created'])]

    def __str__(self):
        return f"order {self.id}"

    def get_total_cost(self):
        return sum(item.cost() for item in self.items.all())

    def get_post_cost(self):
        weight = sum(item.get_weight() for item in self.items.all())
        if weight < 1000:
            return 20000
        elif 1000 <= weight <= 2000:
            return 30000
        else:
            return 50000

    def get_final_cost(self):
        price = self.get_post_cost() + self.get_total_cost()
        return price


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="order_items", on_delete=models.CASCADE)
    price = models.PositiveIntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1)
    weight = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.id)

    def cost(self):
        return self.price * self.quantity

    def get_weight(self):
        return self.weight * self.quantity

order/forms.py
from django import forms
from .models import Order


class PhoneVerificationForm(forms.Form):
    phone = forms.CharField(max_length=11, label="phone")


class OrderCreationForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone', 'address', 'postal_code', 'province', 'city']

order/views.py
import random
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from account.models import ShopUser
from cart.cart import Cart
from .forms import PhoneVerificationForm, OrderCreationForm
from .models import OrderItem, Order
from django.conf import settings
import requests
import json
from django.http import HttpResponse


def verify_phone(request):
    if request.user.is_authenticated:
        return redirect('order:create_order')
    if request.method == "POST":
        form = PhoneVerificationForm(request.POST)
        if form.is_valid():
            phone = form.cleaned_data['phone']
            if ShopUser.objects.filter(phone=phone).exists():
                messages.error(request, 'this phone number is already registered')
                return redirect('order:verify_phone')
            else:
                tokens = {'token': ''.join(random.choices('0123456789', k=6))}
                request.session['verification_code'] = tokens['token']
                request.session['phone'] = phone
                # send sms
                messages.success(request, 'verification code has been sent successfully')
                return redirect('order:verify_code')
    else:
        form = PhoneVerificationForm()
    return render(request, 'verify-phone.html', {'form': form})


def verify_code(request):
    if request.method == "POST":
        code = request.POST.get('code')
        if code:
            verific_code = request.session['verification_code']
            phone = request.session["phone"]
            if code == verific_code:
                user = ShopUser.objects.create_user(phone=phone)
                user.set_password(random.randrange(0, 9))
                user.save()
                # send sms
                login(request, user)
                del request.session['verification_code']
                del request.session['phone']
                return redirect("shop:products")
            else:
                messages.error(request, 'code is incorrect')
    return render(request, 'verify-code.html')


@login_required
def create_order(request):
    cart = Cart(request)
    if request.method == "POST":
        form = OrderCreationForm(request.POST)
        if form.is_valid():
            order = form.save()
            order.buyer = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'], weight=item['weight'])
            cart.clear()
            request.session['order_id'] = order.id
            return redirect("order:request")
    else:
        form = OrderCreationForm()
    return render(request, 'order-create.html', {'form': form, 'cart': cart})


if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'

ZP_API_REQUEST = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://{sandbox}.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://{sandbox}.zarinpal.com/pg/StartPay/"

CallbackURL = 'http://127.0.0.1:8000/order/verify/'


def send_request(request):
    order = get_object_or_404(Order, id=request.session["order_id"])
    description = ""
    for item in order.items.all():
        description += item.product.name + ","
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": order.get_final_cost(),
        "Description": description,
        "Phone": request.user.phone,
        "CallbackURL": CallbackURL,
    }
    data = json.dumps(data)
    # set content length by data
    headers = {'accept': 'application/json', 'content-type': 'application/json', 'content-length': str(len(data))}
    try:
        response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)

        if response.status_code == 200:
            response_json = response.json()
            authority = response_json['Authority']
            if response_json['Status'] == 100:
                return redirect(ZP_API_STARTPAY + authority)
            else:
                return HttpResponse('Error')
        return HttpResponse('response failed')
    except requests.exceptions.Timeout:
        return HttpResponse('Timeout Error')
    except requests.exceptions.ConnectionError:
        return HttpResponse('Connection Error')


def verify(request):
    order = get_object_or_404(Order, id=request.session["order_id"])
    data = {
        "MerchantID": settings.MERCHANT,
        "Amount": order.get_final_cost(),
        "Authority": request.GET.get('Authority'),
    }
    data = json.dumps(data)
    # set content length by data
    headers = {'accept': 'application/json', 'content-type': 'application/json', 'content-length': str(len(data))}
    try:
        response = requests.post(ZP_API_VERIFY, data=data, headers=headers)
        if response.status_code == 200:
            response_json = response.json()
            reference_id = response_json['RefID']
            if response_json['Status'] == 100:
                for item in order.items.all():
                    item.product.inventory -= item.quantity
                    item.product.save()
                order.paid = True
                order.save()
                return render(request, 'payment-tracking.html',
                              {'success': True, "RefID": reference_id, "order_id": order.id})
            else:
                return render(request, 'payment-tracking.html', {'success': False})
        del request.session["order_id"]
        return HttpResponse('response failed')
    except requests.exceptions.Timeout:
        return HttpResponse('Timeout Error')
    except requests.exceptions.ConnectionError:
        return HttpResponse('Connection Error')


def orders_list(request):
    user = request.user
    orders = Order.objects.filter(buyer=user)
    return render(request, "order-list.html", {"orders": orders})


def order_detail(request, id):
    order = get_object_or_404(Order, id=id)
    return render(request, 'order-detail.html', {'order': order})

order/templates/order-create.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Create order{% endblock %}
{% block content %}
    <ul>
        {% for item in cart %}
            <li>
                {{ item.quantity }} x {{ item.product.name }}
                {{ item.total }}
            </li>
        {% endfor %}
    </ul>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Order</button>
    </form>
{% endblock %}

order/templates/order-detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Order detail{% endblock %}
{% block content %}
    {% for item in order.items.all %}
        Name: {{ item.product.name }}
        <br>
        Quantity: {{ item.quantity }}
        <br>
        Price: {{ item.price }}
        <br>
        Weight: {{ item.weight }}
        <hr>
    {% endfor %}
    Date of order: {{ order.created }}
    <br>
    Address: {{ order.address }}
{% endblock %}

order/templates/order-list.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Your orders{% endblock %}
{% block content %}
    <h2>List of your orders</h2>
    <table style="border: 1px black solid">
        <thead>
        <tr>
            <th>number of order</th>
            <th>date of order</th>
            <th>status of order</th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td><a href="{% url 'order:order_detail' order.id %}">{{ order.id }}</a></td>
                <td>{{ order.created }}</td>
                {% if order.paid %}
                    <td>Success</td>
                {% else %}
                    <td>Failed</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

order/templates/payment-tracking.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Payment{% endblock %}
{% block content %}
    {% if success %}
        <p>Payment was successful</p>
        <p>Pay number: {{ RefID }}</p>
        <p>Order number: {{ order_id }}</p>
    {% else %}
        <p>Payment failed!</p>
    {% endif %}
    <a href="{% url "shop:products" %}">Return to the list of products</a>
{% endblock %}

order/templates/verify-code.html
<h2>Verification code</h2>
{% for message in messages %}
    {{ message }}
{% endfor %}
<form method="post">
    {% csrf_token %}
    <input type="text" name="code" aria-label="Verification code">
    <button type="submit">Verify</button>
</form>

order/templates/verify-phone.html
<h2>Phone verification</h2>
{% for message in messages %}
    {{ message }}
{% endfor %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Verify</button>
</form>