cart/urls.py
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('update_quantity/', views.update_quantity, name="update_quantity"),
    path('remove_item/', views.remove_item, name="remove_item")
]

sabzshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('shop.urls', namespace='shop')),
    path("cart/", include('cart.urls', namespace='cart')),
    path('order/',include('order.urls',namespace="order"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "shop"
urlpatterns = [
    path('', views.profile, name="profile"),
    path('products/', views.product_list, name='products'),
    path('products/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('products_filter/<str:ordering>/', views.product_list, name='products_by_filter'),
    path('product/<int:id>/<slug:slug>', views.product_detail, name='product'),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.register, name='register'),

]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

    def __iter__(self):
        yield self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(max_length=3000)
    inventory = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)
    off = models.PositiveIntegerField(default=0)
    new_price = models.PositiveIntegerField(default=0)
    weight = models.PositiveIntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product', args=[self.id, self.slug])


class ProductFeature(models.Model):
    product = models.ForeignKey(Product, related_name='features', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    value = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Image(models.Model):
    post = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    file = models.ImageField(upload_to='post_images/%y/%m/%d', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

shop/forms.py
from django import forms
from account.models import ShopUser
from re import match


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=250, widget=forms.PasswordInput, required=True, label='password')
    password2 = forms.CharField(max_length=250, widget=forms.PasswordInput, required=True, label='repeat password')

    class Meta:
        model = ShopUser
        fields = ['phone', 'first_name', 'last_name']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Please enter your password correctly ")
        if cd['password2'].isdigit():
            raise forms.ValidationError("password must contain a letter")
        if len(cd['password2']) < 8:
            raise forms.ValidationError("password should be at least 8 character")
        if not bool(match(r'\w*[A-Z]w*', cd['password2'])):
            raise forms.ValidationError("Your password must contain capital letters")
        return cd['password2']

shop/views.py
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404
from .models import *
from django.core.paginator import Paginator
from .forms import UserRegisterForm


def profile(request):
    user = request.user
    return render(request, 'shop/profile.html', {'user': user})


def product_list(request, category_slug=None, ordering=None):
    password = "Mahdi"
    category = None
    categories = Category.objects.all()
    products = Product.objects.prefetch_related('category').all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    if ordering == "recent":
        products = products.order_by('-created')
    if ordering == "old":
        products = products.order_by('created')
    elif ordering == "expensive":
        products = products.order_by('-new_price')
    elif ordering == "cheap":
        products = products.order_by('new_price')
    paginator = Paginator(products, 6)
    page_number = request.GET.get('page', 1)
    products = paginator.page(page_number)
    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    category = product.category
    similar_products = Product.objects.filter(category__name__in=category).exclude(id=product.id)
    return render(request, 'shop/detail.html', {'product': product, 'similar_products': similar_products})


def user_logout(request):
    logout(request)
    return render(request, 'registration/logged_out.html')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})

shop/templates/shop/detail.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
    <h2>{{ product.name }}</h2>
    {% for img in product.images.all %}
        <img src="{{ img.file.url }}" alt="Not found" style="width: fit-content" height="150px">
    {% endfor %}
    <br>
    Category : {{ product.category }}
    <br>
    Description : {{ product.description }}
    <br>
    Inventory : {{ product.inventory }}
    <br>
    Price:
    <del>{{ product.price }}</del> | {{ product.off }} OFF
    <br>
    New price : {{ product.new_price }}
    <br>
    Weight : {{ product.weight }}
    <br>
    <button type="button" id="add-cart">
        Add to cart
    </button>
    <hr>
    Similar Products
    <br>
    {% for product in similar_products %}
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <img src="{{ product.images.first.file.url }}" alt="Not found" style="width: fit-content" height="150px">
        <br>

    {% endfor %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function () {
            $('#add-cart').click(function () {
                $.ajax({
                    type: 'POST',
                    url: '{% url 'cart:add_to_cart' product.id %}',
                    data: {'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    success: function (data) {
                        $('#item-count').text(data.item_count)
                        $('#total-price').text(data.total_price)
                    }
                });
            });
        });
    </script>
{% endblock %}

shop/templates/shop/list.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}product list{% endblock %}
{% block content %}
    Filters:
    <a href="{% url 'shop:products_by_filter' 'recent' %}">Most recent</a> |
    <a href="{% url 'shop:products_by_filter' 'expensive' %}">Most expensive</a> |
    <a href="{% url 'shop:products_by_filter' 'cheap' %}">Most cheap</a> |
    <a href="{% url 'shop:products_by_filter' 'old' %}">Most old</a>
    <br>
    {% if category %}
        <h2>products in {{ category.name }} category</h2>
        {% for product in products %}
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            <img src="{{ product.images.first.file.url }}" alt="Not found" style="width: fit-content" height="150px">
            <hr>
        {% endfor %}
    {% else %}
        <h2>products</h2>
        {% for product in products %}
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            <br>
            <img src="{{ product.images.first.file.url }}" alt="Not found" style="width: fit-content" height="150px">
            <hr>
        {% endfor %}
    {% endif %}
    <br>
    <h2>Categories</h2>
    {% for category in categories %}
        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
        <hr>
    {% endfor %}
    {% include 'partials/pagination.html' with page=products %}
{% endblock %}

shop/templates/shop/profile.html
{% extends 'parent/base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content %}
    <h1>Profile</h1>
    <h2>Hi {{ user.first_name }} {{ user.last_name }}</h2>
    {% if user.first_name %}
        <a href="{% url 'shop:logout' %}">logout</a>
    {% else %}
        <a href="{% url 'shop:login' %}">login</a> | <a href="{% url 'shop:register' %}">Create account</a>
    {% endif %}
{% endblock %}